---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account
  namespace: bank
  labels:
    account: account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: bank
  labels:
    app: account
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account
      version: v1
  template:
    metadata:
      namespace: bank
      labels:
        app: account
        version: v1
    spec:
      serviceAccountName: account
      containers:
        - name: account
          image: ghcr.io/dafuemu/spring_app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080