---
apiVersion: v1
kind: Namespace
metadata:
  name: bank
  labels:
    name: bank
---
apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: bank
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: ghcr.io/dafuemu/app:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80