apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: account
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50
