apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: account
                port:
                  number: 8080