name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Validate gradle"
        uses: gradle/wrapper-validation-action@v1

      - name: "Setup Java"
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: "Initialize Gradle dependencies cache"
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle') }}

      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2

      - name: "Test and Build"
        run: ./gradlew build

      - name: "Package application"
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/libs

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Docker build and push"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/dafuemu/spring_app:latest
            ghcr.io/dafuemu/spring_app:1.0.0

      - name: "Set up kubectl"
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: k8s-cluster

      - name: "Deploy"
        run: cd k8s && kubectl apply -f .