name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Setup Java"
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: "Initialize Gradle dependencies cache"
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle') }}

      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: "Build and Test with Gradle"
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build
          - Package application

      - name: "Package application"
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - name: "Docker build and push"
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/dafuemu/spring_app:latest
            ghcr.io/dafuemu/spring_app:1.0.0